spring.application.name=springAi

# Add your OpenAI API key here
spring.ai.openai.api-key=sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Add your Anthropic API key here
spring.ai.anthropic.api-key=sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Add your Ollama model name here
spring.ai.ollama.chat.options.model=deepseek-r1:latest
